; This is a default paramters files that shows the minimum parameters that needs to be set.
; Please copy it outside of the HOBL directory and name it something specific to the device it will be associated with,
; i.e. "dut7_profile.ini".  You should have a separate file for each DUT (Device Under Test)
; you will be testing because you shouldn't attempt to share any of the accounts across multiple DUT's.
;
; The format consists of "sections" in square brackets.  Sections refer to a particular
; scenario or tool, except [global] which has parameters that pertain to all.  The parameters below each 
; section pertain to that section.  Parameters are specified as "<key>: <value>". Ex:
;   dut_ip: 127.0.0.1
; Values can contain spaces.  Semicolon indicates a commment, but must be on it's own line.

[global]
; The directory to write results.  Typically, this should be changed for each study with a
; path that includes the name of the study.  To prevent the need to manually change this
; dir, variables can be specified in square brackets in the path.  Any global paramter can be
; a path variable, as the following special ones: [OS_BUILD], [LKG].  Example:
; result_dir: c:\hobl_results\[windows_version]\[dut_name]\HOBL\[OS_BUILD]
result_dir=c:\hobl_results
; Name of Device Under Test, as reported by "hostname" command.  The name of the DUT will be changed
; to the name you put here.  Make sure names do not include '-' or spaces.  If you want to keep this current DUT host name,
; this can be omitted.
dut_name=
; IP address of the Device Under Test.  Can be a name if local network supports DNS sufficiently.
dut_ip=127.0.0.1
; Microsoft account associated with Device Under Test
msa_account=
; Password of Device Under Test.  This is only used by dut_setup to configure auto-logon.
dut_password=
; Wireless LAN name (SSID) to be used by Device Under Test
dut_wifi_name=
; Wireless LAN password for above SSID, used to auto connect to Wi-Fi.
dut_wifi_password=
; Architecture of Device Under Test, valid values are: x64 or arm64.
dut_architecture=
; List any tools that should be run with each power scenario, in a space-separated list.  Available tools are in the "tools" directory.  These are the minimally required ones:
tools=display_brightness run_report
; List any tools that should be run with each prep scenario, in a space-separated list.  Available tools are in the "tools" directory.  These are the minimally required ones:
prep_tools=

; The following callbacks can be used to execute shell commands at specific events, to enable integration with 
; external programs and equipment.  For each callback below, the path to the test results will automatically be 
; added by the system with a seprating space.  The values below are exmples used by Microsoft to do socket
; commmunication with separate tools.
;
; callback_test_begin: python msft_skt_client.py -port 4770 DAQ_Start
; callback_test_end: python msft_skt_client.py -port 4770 DAQ_Stop
; callback_data_ready: python msft_skt_client.py -port 4770 Data_Ready
; callback_test_fail: python msft_skt_client.py -port 4770 Reset

; Specify a host shell command to run on the device charger
charge_on_call=

; Specify a host shell command to run off the device charger
charge_off_call=

pre_run_delay=0
post_run_delay=60

[display_brightness]
; Specify the display brightness slider setting.  For HOBL compliant testing, specify a value that corresponds to 150 nits.
brightness=65

[netflix]
; You need to have a Netflix account to run the Netflix scenario.  Provide username and password here.
netflix_username=
netflix_password=

[office_install]
; Set activate to 0 if you just want to use the 5-day free trial of Office365, or you are internal to Microsoft.
activate=0

; Add any additional sections for tools or scenarios where you want to change the values from default.
